### ISSUE TITLE
DoubleSlider Elements Not Overlapping

### ISSUE THREAD

**Issue by euphbriggs** [carwow/elm-slider#18]
Thank you for creating this package. I've used SingleSlider in the past, and it's worked out very well for me. I'm attempting to use the DoubleSlider, but I'm running into an issue.

Without applying any CSS styling, the two elements in the DoubleSlider are visually separated, but function as I would expect. If I adjust the CSS so that they're overlapping, the HighValue slider functions correctly but I'm not able to change the LowValue slider.

I created an Ellie App (based on the SingleSlider example in the README) to demonstrate: https://ellie-app.com/6b8hfmRPKrra1

In the HTML section, if you remove the CSS, you can see the visual gap. I see the same thing in my application.

Is this a bug, or am I missing a required step?

**Comment by euphbriggs** [comment]
I found some CSS that make it look the way I expected it to. Here's a link to the [updated Ellie project](https://ellie-app.com/6c4Mxpb4XYha1).

For users in the future, I added this CSS to restrict the ability to change the values to the slider thumbs.

```CSS
    .input-range-container > input.input-range.input-range--second {
      margin-left: -130px;
    }

    .input-range-container input[type='range'] {
      pointer-events: none;
    }
    
    .input-range-container input[type='range']::-webkit-slider-thumb {
        pointer-events: all;
    }
```
